name: CI - Markdown and Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli
          npm install -g cspell

      - name: Run markdownlint
        run: markdownlint "**/*.md"

      - name: Run cspell
        run: cspell "**/*.md"
