name: CI - Markdown Lint & Spell Check

on: 
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1
        with:
          config: .markdownlint.yml

      - name: Spell Check
        uses: rojopolis/spellcheck-github-actions@0.34.0
        with:
          config_path: .spellcheck.yml

      - name: Test Step
        run: echo " Workflow is running fine"

